# Generated by Django 4.1 on 2024-08-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_knowledgebasesection_knowledgebasearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_base/files/'),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='knowledge_base/images/'),
        ),
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.knowledgebasesection'),
        ),
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
