# Generated by Django 4.1 on 2024-09-09 13:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_knowledgebasearticle_attached_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dashboard.knowledgebasesection'),
        ),
        migrations.AlterField(
            model_name='knowledgebasesection',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowledgebasesection',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
